# Generated by Django 4.1.2 on 2022-11-16 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_link',
        ),
    ]
